### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by zplusfour** [slice-lang/slice-vm#1]
èèè cawn i hewp uwu cweating a 📦 managew fow thiws?

**Comment by firefish111** [comment]
@zplusfour wut wait this isn't a working language... also I was intending
to make dusk the default package manager for this...

**Comment by firefish111** [comment]
We are also trying to make  a transpiler for slice, and you can help with that (it can be in Go) @zplusfour

**Comment by zplusfour** [comment]
I KNOW SOME RUST UWU

**Comment by firefish111** [comment]
Ok :) But as you know more GoLang than I do you can try to make a
transpiler...

**Comment by zplusfour** [comment]
Ok

**Comment by zplusfour** [comment]
dang we were friends on this day

**Comment by firefish111** [comment]
you dare insult poop inc
